# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8505b98f6295a8c74dee4de3318845a4cb87e3ee8ebfb0ec44b6bd2e02976e0690dfba61e652fedbdeedc517e92595e63f3ed0bbf04e214db035597bd355217c

test:
  secret_key_base: 7b2a623f014953fc0a558a1df997f75ccfeb24e00dd0de0a98377c58020c16dedb6374a37b170d30ff2612048102d08ac5fc8eb6f2093d2b1bfcde6de4718ffe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
